# Generated by Django 5.2.8 on 2025-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_user_adresse_user_bailleur_request_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cni_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/cni/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='titre_foncier',
            field=models.FileField(blank=True, null=True, upload_to='documents/titre/'),
        ),
    ]
