# Generated by Django 5.2.8 on 2025-12-07 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.PositiveIntegerField(help_text='Prix par mois en FCFA')),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.CharField(blank=True, max_length=300)),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('chambres', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meuble', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('images', models.JSONField(default=list)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_annonces', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='listings.categorie')),
            ],
            options={
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_creation'],
            },
        ),
    ]
