# Generated by Django 5.2.8 on 2025-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Annonce', 'verbose_name_plural': 'Annonces'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='icone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='annee_construction',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='balcon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='caution',
            field=models.PositiveIntegerField(default=0, help_text='Caution (optionnel)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='chauffage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='climatisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='cuisine_equipee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='date_disponibilite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='etage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='favoris',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='machine_a_laver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='piscine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='salles_de_bain',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='television',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='surface',
            field=models.PositiveSmallIntegerField(blank=True, help_text='En m²', null=True),
        ),
    ]
